apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-rc-pod
    spec:
      containers:
      - name: webapp
        image: arungupta/wildfly-app:1
        ports:
        - containerPort: 8080
