apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-rc
  labels:
    name: couchbase
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: couchbase
    spec:
      containers:
      - name: couchbase-rc-pod
        image: arungupta/couchbase
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 11210
